### ISSUE TITLE
Why was authorization from individual API call?

### ISSUE THREAD

**Issue by v-kumar** [square/connect-ruby-sdk#28]
We use Square on behalf of multiple merchants and our access_tokens are different for each merchant.

Removing the authorization from individual calls and making it VM wide global makes it impossible for us to migrate to versions > 2.0.x.

How do you recommend those who access Square on behalf of multiple merchants deal with this?

**Comment by frojasg** [comment]
Hi @v-kumar, 

Yes, you can create API clients with a specific configuration in the following way:
```ruby
# creates configuration with specific access token
configuration = SquareConnect::Configuration.new do |config|
  config.access_token = 'YOUR ACCESS TOKEN'
end
# create client for specific merchant
client = SquareConnect::ApiClient.new(configuration)
# create specific api client
location_api = SquareConnect::LocationsApi.new(client)
```

**Comment by frojasg** [comment]
If you have further questions feel free to re-open this issue again or use [our stackoverflow tag](https://stackoverflow.com/questions/tagged/square-connect)
