### ISSUE TITLE
Allow upgrade to Ruby 2.4 and JSON 2

### ISSUE THREAD

**Issue by v-kumar** [square/connect-ruby-sdk#36]
json 2 is pretty much required now for full JSON RFC compliance and compatibility with ruby 2.4.

Most rails gems now support either 1.8 or 2.0.

Keeping the ceiling at 1.8 is preventing us from upgrading other gems and to ruby 2.4/2.5 versions. Can we be bit more generous with json dependency? This is similar to: https://github.com/Azure/autorest/issues/476

Ruby 2.5 ships with json 2.1 and, Ruby 2.4 ships with json 2.0.x.

It would be better to skip the dependency altogether or support higher versions.

**Comment by javierjulio** [comment]
Yes I believe some gems don't even require the dependency as it also causes on other platforms like Windows. I've seen this [change go into libraries like Sidekiq](https://github.com/mperham/sidekiq/issues/2743). An update to allow json 1.8 or 2.0 would be greatly appreciated.

**Comment by havenwood** [comment]
The 1.8 branch of the JSON gem added support for Ruby 2.4+ in version 1.8.5.

**Comment by havenwood** [comment]
Even though it works as-is, I think it's a good idea to bump the JSON gem version!

**Comment by TranqTech** [comment]
THIS. Absolutely this. I'd love to be able to actually install/use square connect, but when it has dependencies that preclude running up to date versions of ruby, or having to run older versions of other gems, it's a complete non-starter. Is there some particular reason the JSON dependency is locked at an out of date version?

**Comment by v-kumar** [comment]
Any update on this?

**Comment by v-kumar** [comment]
Hello, There are at least two PRs referencing this and including my issue, 3. There is no reason to have 1.8.3 dependency. It makes upgrading to ruby 2.4, many of the rails ecosystem gems impossible. Can we get an update please?

**Comment by havenwood** [comment]
@v-kumar Hi! Apologies for the delay on this. The JSON gem version will be bumped in an upcoming release.

**Comment by javierjulio** [comment]
@havenwood thanks! That would be most helpful. 😄

**Comment by havenwood** [comment]
Closed by d5bcdca14e52fc2a3f8ac747572eabc82ab99400.

**Comment by v-kumar** [comment]
This is awesome. Thanks @havenwood.
