### ISSUE TITLE
Allow use of 2 API key/accounts in a single app

### ISSUE THREAD

**Issue by otang** [square/connect-ruby-sdk#43]
At the moment is seems that `SquareConnect.configure` will change the config class, making it very difficult to have two SquareConnect instances that use different tokens.

Do you guys have any suggestion as to how best architect something like this?

Thank you.

**Comment by StephenJosey** [comment]
If you're trying to allow multiple accounts to use your application, you should definitely checkout out our `OAuth API`: https://docs.connect.squareup.com/basics/oauth/overview

That aside, presumably you would have some kind of authorization on your application. In its most basic form you would have a username/password and a database with said information (linked to their access token). So when the user logs into your application, you would set the configuration to use their access token immediately. Let me know if you need any clarification about this.

**Comment by otang** [comment]
@StephenJosey thank you for the response.
