### ISSUE TITLE
Square API errors

### ISSUE THREAD

**Issue by kuranovandry** [square/connect-ruby-sdk#73]
Hello.

When I'm using [RenewTokenRequest](https://github.com/square/connect-ruby-sdk/blob/master/lib/square_connect/models/renew_token_request.rb), I'm getting this error:
```rb
SquareConnect::ApiError:
Bad Request - {
  "message": "cannot renew revoked token",
  "type": "bad_request"
}
```
Doesn't [RenewTokenResponse](https://github.com/square/connect-ruby-sdk/blob/master/lib/square_connect/models/renew_token_response.rb) (and other `response` objects) supposed to handle such cases and contain some [Error](https://github.com/square/connect-ruby-sdk/blob/master/lib/square_connect/models/error.rb) with coresponding code, e.g. [ACCESS_TOKEN_REVOKED](https://github.com/square/connect-ruby-sdk/blob/master/lib/square_connect/models/error_code.rb#L18)? 
Because for now, I can only parse response for this message, which seems like a bad solution to me.
Or is there a better way to handle token revocation form Square dashboard, without getting it on the runtime?

Also, [Error#handlingerrors](https://github.com/square/connect-ruby-sdk/blob/master/docs/Error.md#handlingerrors) refers to nowhere.

**Comment by StephenJosey** [comment]
In this particular case the code is `BAD_REQUEST`. You're trying to renew on a revoked token. I believe you would get `ACCESS_TOKEN_REVOKED` if you called an API endpoint with a revoked endpoint.

**Comment by kuranovandry** [comment]
@StephenJosey, yes, it does, but also without wrapping them into `Error` instance (tried with list_locations endpoint).
Anyway, is there a better practice to handle revoked token (from Square dashboard, like webhook or so), or it could be known only on making request to Square API?

**Comment by StephenJosey** [comment]
@kuranovandry unfortunately there's no way to know if a token was revoked without explicitly receiving that message upon calling an API endpoint.

**Comment by kuranovandry** [comment]
Ok, thank you.
