### ISSUE TITLE
How to add `Tips` through the Square API

### ISSUE THREAD

**Issue by gnumarcelo** [square/connect-ruby-sdk#80]
Hi, I am using the Square's OrderAPI + TransactionAPI to handle my eCommerce checkout and everything is working great so far.
However, I've just received a requirement from my client to add the tip section to the checkout, where customers will inform how much tip they will give. Is it something doable using the current Square's Api?

**Comment by havenwood** [comment]
You can add tips with the `tip_money` keyword argument if you use the [V1Payment API](https://github.com/square/connect-ruby-sdk/blob/master/docs/V1Payment.md).

**Comment by deanpapastrat** [comment]
Hey @gnumarcelo, this is not currently doable today. I've passed your feedback onto our Payments team.
