### ISSUE TITLE
Redirect url format

### ISSUE THREAD

**Issue by imgarylai** [square/connect-ruby-sdk#84]
https://github.com/square/connect-ruby-sdk/blob/2843d8a0c3c0e9ead91ba0e04196f26747b72eb5/lib/square_connect/models/create_checkout_request.rb#L33-L34

Is this documentation still correct? I have tested it in the sandbox. The redirec_url, however, only contains`checkoutId` and `transactionId`.

**Comment by deanpapastrat** [comment]
Sandbox responses for the Checkout API may not be equivalent to production responses, currently. I believe it will return an Order ID in production. If not, you can call `RetreiveTransaction` and then get the Order ID off of it.
