### ISSUE TITLE
Invalid Enum for OrderServiceChargeCalculationPhase

### ISSUE THREAD

**Issue by jakejcheng** [square/connect-ruby-sdk#85]
I keep on getting this error for calculation phase. Tried "TOTAL_PHASE" and SquareConnect::OrderServiceChargeCalculationPhase::TOTAL_PHASE (which gives "TOTAL_PHASE") but still getting the error below.

Bad Request - {"errors":[{"category":"INVALID_REQUEST_ERROR","code":"INVALID_ENUM_VALUE","detail":"`TOTAL_PHASE` is not a valid enum value for `order.order.service_charges[0].calculation_phase`.","field":"order.order.service_charges[0].calculation_phase"}]}

**Comment by StephenJosey** [comment]
Thanks for sharing! We'll take a look and follow-up once we have more information.

**Comment by jakejcheng** [comment]
This is fixed now. Thanks!
